import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/UI/layout/header";
import { Providers } from "../providers/provider";
import { siteConfig } from "@/config/site.config";
import { layoutConfig } from "@/config/layout.config";
import { SessionProvider } from "next-auth/react";
import AppLoader from "@/hoc/app-loader";
import Title from "@/components/UI/layout/title";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AutoToshka.ru",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SessionProvider>
            <AppLoader>
              <Header />
              <Title />
              <main
                className="flex flex-col max-w-5xl px-40px mx-auto w-full justify-start items-center my-6"
                style={{ minHeight: `calc(100vh - ${layoutConfig.headerHeight} - ${layoutConfig.footerHeight})` }}
              >
                {children}
              </main>
              <footer
                className="flex justify-center items-center"
                style={{ height: layoutConfig.footerHeight }}
              >
                <p className="">{siteConfig.description}</p>
              </footer >
            </AppLoader>
          </SessionProvider>
        </Providers>
      </body>
    </html>
  );
}
